import Head from "next/head";
import { useRouter } from "next/router"
const navitmelist = [
  { ScreenName: "Home", Path: "/" },
  { ScreenName: "contactus", Path: "/contactus" },
  { ScreenName: "localposts", Path: "/localposts" },
  { ScreenName: "blog", Path: "/blog" },
  { ScreenName: "localposts", Path: "/localposts" },
  { ScreenName: "Contact Us", Path: "/contactus" },
  
];
export default function Home() {

  const router=useRouter();
  const handleplaceorder=()=>{
    console.log("place order")
    router.push('/product')
  }
  return(
  <>
  <Head>
        <title>learn Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div>home</div>
  </>
  )

}